# Generated by Django 5.2.12 on 2026-04-01 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('loan_approved', 'Loan Approved'), ('loan_funded', 'Loan Funded'), ('payment_reminder', 'Payment Reminder'), ('payment_due', 'Payment Due'), ('payment_failed', 'Payment Failed'), ('contract_sent', 'Contract Sent'), ('welcome', 'Welcome')], default='manual', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communications_communicationtemplate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('from_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('to_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('from_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('to_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField()),
                ('html_content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='Twilio/SendGrid message ID', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='accounts.customer')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='loans.loan')),
            ],
            options={
                'db_table': 'communications_communication',
                'ordering': ['-created_at'],
            },
        ),
    ]
