# Generated by Django 5.2.12 on 2026-07-08 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customer_status"),
        ("communications", "0002_incoming_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="communication",
            name="is_unknown_sender",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="communication",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communications",
                to="accounts.customer",
            ),
        ),
    ]
