# Generated by Django 5.2.12 on 2026-04-01 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_url', models.URLField(help_text='URL to signed/unsigned contract PDF')),
                ('template_version', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('signed', 'Signed'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('signature_request_id', models.CharField(blank=True, help_text='DocuSign/HelloSign request ID', max_length=255, null=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='loans.loan')),
            ],
            options={
                'db_table': 'contracts_contract',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('loan_type', models.CharField(help_text='NoJuice, Payday, etc.', max_length=20)),
                ('province', models.CharField(blank=True, help_text='Province-specific template', max_length=2, null=True)),
                ('version', models.CharField(max_length=50)),
                ('template_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contracts_contracttemplate',
                'ordering': ['-created_at'],
                'unique_together': {('loan_type', 'province', 'version')},
            },
        ),
    ]
