# Generated by Django 5.2.12 on 2026-05-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contracttemplate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contract',
            name='document_url',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='sent_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='signature_request_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='template_version',
        ),
        migrations.AddField(
            model_name='contract',
            name='accepted_banking_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='accepted_credit_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='accepted_electronic_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='agreement_text',
            field=models.TextField(default='\nDEMONSTRATIVE LOAN AGREEMENT\n\nThis agreement is a placeholder for demonstration and product testing purposes.\n\nBy continuing, you confirm that:\n1. The information you provided in your application is accurate.\n2. You authorize review of your banking information for eligibility assessment.\n3. You understand that submitting this agreement does not guarantee approval or funding.\n4. Final approval, funding, repayment schedule, and legal terms may be confirmed later.\n5. The legal team will replace this text with the final contract language before production use.\n\nDEMONSTRATIVE REPAYMENT SCHEDULE\n\nRequested amount: shown in your portal.\nEstimated fees: shown in your portal.\nEstimated repayment: to be confirmed before funding.\nPayment method: bank account selected during verification.\n'),
        ),
        migrations.AddField(
            model_name='contract',
            name='agreement_version',
            field=models.CharField(default='demo-v1', max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='typed_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('void', 'Void')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='loan_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='province',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='template_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='version',
            field=models.CharField(default='demo-v1', max_length=50),
        ),
    ]
