# Generated by Django 5.2.12 on 2026-07-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_alter_contracttemplate_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="agreement_text",
            field=models.TextField(
                default="Loan agreement content is generated dynamically at preview/sign time."
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="agreement_version",
            field=models.CharField(default="mohawk-arrive-v1", max_length=50),
        ),
    ]
