# Generated by Django 5.2.12 on 2026-05-06 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AuthOTPChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('signup_phone', 'Signup Phone Verification'), ('login_email', 'Login Email OTP'), ('login_sms', 'Login SMS OTP')], db_index=True, max_length=30)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('code_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('locked', 'Locked'), ('used', 'Used')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'accounts_auth_otp_challenge',
                'indexes': [models.Index(fields=['identifier', 'purpose', 'status', '-created_at'], name='acct_otp_lookup_idx')],
            },
        ),
    ]
