# Generated by Django 5.2.12 on 2026-05-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_phone_normalized_user_phone_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='requested_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='authotpchallenge',
            name='purpose',
            field=models.CharField(choices=[('signup_phone', 'Signup Phone Verification'), ('login_email', 'Login Email OTP'), ('login_sms', 'Login SMS OTP'), ('password_reset_email', 'Password Reset Email OTP'), ('password_reset_sms', 'Password Reset SMS OTP')], db_index=True, max_length=30),
        ),
    ]
