# Generated by Django 5.2.12 on 2026-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customer_status_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="flinks_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="flinks_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
