# Generated by Django 5.2.12 on 2026-06-25 18:42

from django.db import migrations, models


def normalize_customer_statuses(apps, schema_editor):
    Customer = apps.get_model("accounts", "Customer")
    valid_statuses = {"active", "collections", "renewals", "refinances"}
    Customer.objects.exclude(status__in=valid_statuses).update(status="active")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_globalsetting"),
    ]

    operations = [
        migrations.RunPython(normalize_customer_statuses, noop_reverse),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("collections", "Collections"),
                    ("renewals", "Renewals"),
                    ("refinances", "Refinances"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
