# Generated by Django 5.2.12 on 2026-08-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_arrive_integration_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="sms_opt_out_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="sms_opted_out",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="sms_opted_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
