# Generated by Django 5.2.12 on 2026-09-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icollector', '0002_disabled_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('blocked', 'Needs review'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16),
        ),
    ]
