# Generated by Django 5.2.12 on 2026-06-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_bankconnection_login_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('connection', 'external_id')},
        ),
    ]
