# Generated by Django 5.2.12 on 2026-07-14 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customer_status"),
        ("banking", "0003_alter_bankaccount_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="use_for_eft_collections",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="use_for_eft_funding",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BankingAnalysisEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("event", models.CharField(max_length=100)),
                (
                    "schema_version",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("report_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "login_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("tag", models.CharField(blank=True, default="", max_length=100)),
                ("decision_1", models.JSONField(blank=True, default=dict)),
                ("decision_2", models.JSONField(blank=True, default=dict)),
                ("primary_bank_account", models.JSONField(blank=True, default=dict)),
                ("report", models.JSONField(blank=True, default=dict)),
                ("final_report_text", models.TextField(blank=True, default="")),
                ("source_transactions", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("analysis_created_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("exception", "Exception")],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                ("eft_setup_incomplete", models.BooleanField(default=False)),
                ("exception_note", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_events",
                        to="banking.bankconnection",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banking_analysis_events",
                        to="accounts.customer",
                    ),
                ),
                (
                    "primary_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_events",
                        to="banking.bankaccount",
                    ),
                ),
            ],
            options={
                "db_table": "banking_bankinganalysisevent",
                "ordering": ["-received_at"],
            },
        ),
    ]
