# Generated by Django 5.2.12 on 2026-04-01 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('loan_created', 'Loan Created'), ('loan_funded', 'Loan Funded'), ('loan_paid_off', 'Loan Paid Off'), ('loan_defaulted', 'Loan Defaulted'), ('loan_renewed', 'Loan Renewed'), ('payment_scheduled', 'Payment Scheduled'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('contract_signed', 'Contract Signed'), ('contract_sent', 'Contract Sent'), ('ibv_completed', 'IBV Completed'), ('bank_connected', 'Bank Connected'), ('comment', 'Comment'), ('sms_sent', 'SMS Sent'), ('sms_received', 'SMS Received'), ('email_sent', 'Email Sent'), ('email_received', 'Email Received'), ('customer_created', 'Customer Created'), ('customer_updated', 'Customer Updated'), ('customer_blocked', 'Customer Blocked'), ('system', 'System Event')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, help_text="User ID or 'system'", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.customer')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='loans.loan')),
            ],
            options={
                'verbose_name_plural': 'Activity histories',
                'db_table': 'activity_activityhistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal note not visible to customer')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.customer')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='loans.loan')),
            ],
            options={
                'db_table': 'activity_comment',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
