# Generated by Django 5.2.12 on 2026-04-01 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('nojuice', 'NoJuice'), ('payday', 'Payday')], default='nojuice', max_length=20)),
                ('principal', models.DecimalField(decimal_places=2, help_text='Amount borrowed', max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Total fee charged', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Principal + Fee', max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Remaining balance', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('contract_sent', 'Contract Sent'), ('contract_signed', 'Contract Signed'), ('funded', 'Funded'), ('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('funding_method', models.CharField(blank=True, choices=[('etransfer', 'Interac e-Transfer'), ('eft', 'EFT / Direct Deposit')], max_length=20, null=True)),
                ('funding_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('contract_id', models.CharField(blank=True, help_text='DocuSign envelope ID', max_length=100, null=True)),
                ('contract_sent_at', models.DateTimeField(blank=True, null=True)),
                ('contract_signed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Account used for funding and PAD collections', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='banking.bankaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.customer')),
            ],
            options={
                'db_table': 'loans_loan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('scheduled', 'Scheduled PAD'), ('manual', 'Manual Payment'), ('etransfer', 'e-Transfer Received')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('nsf', 'NSF'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Date payment is scheduled for')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'db_table': 'loans_payment',
                'ordering': ['scheduled_date', '-created_at'],
            },
        ),
    ]
