# Generated by Django 5.2.12 on 2026-04-02 19:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FundedPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('etransfer', 'Interac e-Transfer'), ('eft', 'EFT / Direct Deposit')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funded_payments', to='loans.loan')),
            ],
            options={
                'db_table': 'loans_funded_payment',
                'ordering': ['-initiated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanStateEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('defaulted', 'Defaulted'), ('reactivated', 'Reactivated'), ('funded', 'Funded'), ('declined', 'Declined'), ('approved', 'Approved'), ('paid_off', 'Paid Off')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_state_events', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_events', to='loans.loan')),
            ],
            options={
                'db_table': 'loans_loan_state_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
