# Generated by Django 5.2.12 on 2026-05-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_is_active_fundedpayment_loanstateevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_signature', 'Pending Signature'), ('ai_approved', 'AI Approved'), ('ai_declined', 'AI Declined'), ('review_required', 'Review Required'), ('human_approved', 'Human Approved'), ('human_declined', 'Human Declined'), ('pending_funding', 'Pending Funding'), ('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'In Collections')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanstateevent',
            name='event_type',
            field=models.CharField(choices=[('pending_signature', 'Pending Signature'), ('contract_signed', 'Contract Signed'), ('ai_approved', 'AI Approved'), ('ai_declined', 'AI Declined'), ('review_required', 'Review Required'), ('human_approved', 'Human Approved'), ('human_declined', 'Human Declined'), ('funded', 'Funded'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted'), ('reactivated', 'Reactivated')], max_length=30),
        ),
    ]
