# Generated by Django 5.2.12 on 2026-05-19 13:08

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_status_alter_loanstateevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanFormula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('loan_type', models.CharField(choices=[('nojuice', 'NoJuice'), ('payday', 'Payday')], default='nojuice', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brokerage_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=6)),
                ('repayment_percent', models.DecimalField(decimal_places=2, default=Decimal('29.00'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loans_loan_formula',
                'ordering': ['principal_amount', 'name'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='formula',
            field=models.ForeignKey(blank=True, help_text='Pricing formula used to calculate this loan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.loanformula'),
        ),
    ]
