# Generated by Django 5.2.12 on 2026-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanformula_loan_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanformula',
            name='default_frequency_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='loanformula',
            name='default_number_of_payments',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
