# Generated by Django 5.2.12 on 2026-06-18 18:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
        ("loans", "0005_loanformula_default_frequency_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "processor_transaction_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("webhook_type", models.CharField(db_index=True, max_length=100)),
                (
                    "event_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, null=True
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("payload_hash", models.CharField(max_length=64, unique=True)),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "loans_webhook_event",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddField(
            model_name="fundedpayment",
            name="collections_account_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fundedpayment",
            name="destination_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="fundedpayment",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_funded_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fundedpayment",
            name="processor_transaction_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="fundedpayment",
            name="zum_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="collections_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Current account used for EFT collections",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collection_loans",
                to="banking.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="collections_account_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="funding_destination",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="loan",
            name="funding_destination_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CollectionPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "processor_transaction_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("returned", "Returned"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("zum_status", models.CharField(blank=True, max_length=100, null=True)),
                ("account_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "initiated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "settlement_due_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("event_history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_collection_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_payments",
                        to="loans.loan",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional scheduled payment this collection attempt is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_attempts",
                        to="loans.payment",
                    ),
                ),
            ],
            options={
                "db_table": "loans_collection_payment",
                "ordering": ["-initiated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionsAccountChangeAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("previous_account", models.JSONField(blank=True, default=dict)),
                ("new_account", models.JSONField(blank=True, default=dict)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collections_account_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "failed_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_change_audits",
                        to="loans.collectionpayment",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections_account_changes",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "db_table": "loans_collections_account_change_audit",
                "ordering": ["-changed_at"],
            },
        ),
    ]
