# Generated by Django 5.2.12 on 2026-07-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0009_loanstateevent_amount_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundedpayment",
            name="method",
            field=models.CharField(
                choices=[
                    ("etransfer", "Interac e-Transfer"),
                    ("eft", "EFT / Direct Deposit"),
                    ("card_issuance", "Card Issuance"),
                    ("arrive_card", "Arrive Card"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fundingmethodrecommendation",
            name="method",
            field=models.CharField(
                choices=[
                    ("etransfer", "Interac e-Transfer"),
                    ("eft", "EFT / Direct Deposit"),
                    ("card_issuance", "Card Issuance"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="funding_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("etransfer", "Interac e-Transfer"),
                    ("eft", "EFT / Direct Deposit"),
                    ("card_issuance", "Card Issuance"),
                    ("arrive_card", "Arrive Card"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
