# Generated by Django 5.2.12 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0010_alter_fundedpayment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundedpayment",
            name="event_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name="fundedpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["processing", "completed"])),
                fields=("loan",),
                name="unique_active_funding_per_loan",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundedpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("processor_transaction_id__isnull", False)),
                fields=("processor_transaction_id",),
                name="unique_funding_processor_tx",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("payment__isnull", False),
                    ("status__in", ["processing", "completed"]),
                ),
                fields=("payment",),
                name="unique_active_collection_per_payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("processor_transaction_id__isnull", False)),
                fields=("processor_transaction_id",),
                name="unique_collection_processor_tx",
            ),
        ),
    ]
