# Generated by Django 5.2.12 on 2026-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0012_rename_nojuice_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="ibv_reset_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="loanstateevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("pending_signature", "Pending Signature"),
                    ("contract_signed", "Contract Signed"),
                    ("ai_decision", "AI Decision"),
                    ("amount_updated", "Amount Updated"),
                    ("human_approved", "Human Approved"),
                    ("human_declined", "Human Declined"),
                    ("ibv_reset", "IBV Reset"),
                    ("funded", "Funded"),
                    ("paid_off", "Paid Off"),
                    ("defaulted", "Defaulted"),
                    ("reactivated", "Reactivated"),
                ],
                max_length=30,
            ),
        ),
    ]
