# Generated by Django 5.2.12 on 2026-08-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0013_loan_ibv_reset_reason_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["scheduled_date", "created_at", "id"]},
        ),
        migrations.RemoveField(
            model_name="loan",
            name="ibv_reset_reason",
        ),
        migrations.AlterField(
            model_name="loanstateevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("pending_signature", "Pending Signature"),
                    ("contract_signed", "Contract Signed"),
                    ("ai_decision", "AI Decision"),
                    ("amount_updated", "Amount Updated"),
                    ("human_approved", "Human Approved"),
                    ("human_declined", "Human Declined"),
                    ("funded", "Funded"),
                    ("paid_off", "Paid Off"),
                    ("defaulted", "Defaulted"),
                    ("reactivated", "Reactivated"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("pending", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("nsf", "NSF"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
