# Generated by Django 5.2.12 on 2026-09-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0020_payment_type_rebate"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="previous_loan",
            field=models.ForeignKey(
                blank=True,
                help_text="Active loan being paid off by this early renewal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewal_loans",
                to="loans.loan",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="renewal_payoff_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Old-loan balance applied at funding (new principal minus this is sent)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
